### ISSUE TITLE
Setup integration testing

### ISSUE THREAD

**Issue by kobutri** [idil-tub/KMeansClustering.jl#10]
- Figure out how to do integration testing in julia. Best practices, can we run these automatically, etc.

**Comment by kobutri** [comment]
use https://github.com/marketplace/actions/workflow-artifact-pull-request-comment or https://github.com/marketplace/actions/post-pr-comment-from-artifact
combined with https://github.com/actions/upload-artifact to setup manual tests, by commenting generated images into prs.

**Comment by Kingsleyyy21** [comment]
I just did some changes.

I conducted some basic tests based on the last version and corrected issues where the tests failed.

- Printing ARI Results without Testing
I modified the code to print the results for the adjusted rand index (ARI), but I did not set up tests for these results.

- Updating CI Configuration File: 
I made some changes to the ci.yml file to enable new functionalities.

1. Uploading Artifacts.
2. Posting PR Comments from Artifacts.

@kobutri @llluww @idil-tub
