### ISSUE TITLE
Write Unit tests

### ISSUE THREAD

**Issue by kobutri** [idil-tub/KMeansClustering.jl#11]
Figure out a small sample of analytically solvable kmeans datasets.

**Comment by idil-tub** [comment]
I've did some research and looked through examples. 

I've came up with the idea writing unit tests on a smaller size of data (for example 100?) focusing on checking things like:
- if the cluster centers have been computed, 
- if labels have been assigned to each point, 
- if labels are within the expected range, 
- if all labels are distinct, 
- if cluster centers are within the range of the data etc.

And some edge cases such as:
- initialization with more clusters than data points,
- single cluster,
- all points are the same,
- completely different clusters,
- no matching clusters

If we also decide to write integration tests to visualize our clusters, we could check the correctness of large datasets with these integration tests.

I've written some mock-up tests that I can show you later in the meeting.

@kobutri @llluww @Kingsleyyy21

**Comment by kobutri** [comment]
use new api
