### ISSUE TITLE
Acquire test data

### ISSUE THREAD

**Issue by kobutri** [idil-tub/KMeansClustering.jl#9]
We can generate some, but we should also use some real world datasets to test on. This should be used for integration test.

**Comment by llluww** [comment]
I found two classical datasets of the real world.

- iris: https://www.kaggle.com/datasets/uciml/iris (we use in the machine learning lecture)
- wine: https://gist.githubusercontent.com/tijptjik/9408623/raw/b237fa5848349a14a14e5d4107dc7897c21951f5/wine.csv

I found three ways to create test dataset.

1. make_blobs
- Advantages: Simple and Intuitive, Controlled Parameters, Realistic for Many Applications
- Disadvantages: Spherical Clusters, Limited Complexity

2. make_moons
- Advantages: Non-Globular Clusters, Challenging Dataset
- Disadvantages: Specific Shape, Limited Use Cases

3. make_circles
- Advantages: Testing Non-Linear Boundaries, Visual Clarity
- Disadvantages: Limited to Circular Patterns, Not Suitable for All Clustering Algorithms

I suggest we can use iris or make_blobs for beginning, these two datasets are more simple and more clear to see our KMeans works right or not. And then, we might use make_moons or wine for testing if our KMeans can work in more complicated datasets.

**Comment by kobutri** [comment]
setup test data (generate test images and save them to file)

**Comment by llluww** [comment]
I generate images and save them to the following destination:.

image/iris/[iris images]
- image/wine/[wine images]
- image/blobs.png
- image/moons.png
- image/circle.png

Iris dataset have 4 features, so make 2-D images of each features. Total there are 6 images. I've also made a composite of each image.
Wine dataset: 13 features -> 156 images + 1 composite image

Iris Results:
![combined_iris_plot](https://github.com/idil-tub/KMeansClustering.jl/assets/79516985/c26bc120-242e-472f-83d8-696699a84563)
![iris_pl_pw](https://github.com/idil-tub/KMeansClustering.jl/assets/79516985/a779100a-0012-4893-8535-1351f9e65743)
